### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by fnesveda** [apify/apify-sdk-python#10]
We absolutely need these if we want to support the library in the long term.

This can be separated to a few parts:
- [x] Create a framework for running integration tests (done in #33)
- [x] Run integration tests in CI
- [x] Write the actual integration tests

We need integration tests for all `Actor` methods, and that should cover the functionality of the whole SDK. We can take inspiration on what to test from the unit tests.

Lifecycle methods
-----------------

- [x] `Actor.init`
- [x] `Actor.exit`
- [x] `Actor.fail`
- [x] `Actor.main`
- [x] `async with Actor`

Environment helpers
-------------------

- [x] `Actor.is_at_home`
- [x] `Actor.get_env`

Storage methods
---------------

- [x] `Actor.open_dataset`
- [x] `Actor.open_key_value_store`
- [x] `Actor.open_request_queue`
- [x] `Actor.push_data`
- [x] `Actor.get_input`
- [x] `Actor.get_value`
- [x] `Actor.set_value`

Event manager methods
---------------------

- [x] `Actor.on`
- [x] `Actor.off`

Client helpers and wrappers
---------------------------

- [x] `Actor.new_client`
- [x] `Actor.start`
- [x] `Actor.call`
- [x] `Actor.call_task`
- [x] `Actor.abort`
- [x] `Actor.metamorph`
- [x] `Actor.reboot`
- [x] `Actor.add_webhook`
- [x] `Actor.set_status_message`

Proxy helpers
-------------

- [x] `Actor.create_proxy_configuration`
