### ISSUE TITLE
Kick off the AutoscaledPool

### ISSUE THREAD

**Issue by vdusek** [apify/apify-sdk-python#119]
### Tasks
- [x] Explore the Apify/Crawlee AutoscaledPool in JavaScript (https://crawlee.dev/api/core/class/AutoscaledPool).
- [x] Figure out how to implement a similar functionality in Python.
- [x] Prepare a PoC of the AutoscaledPool for Python SDK.
- [x] Measure the performance of the PoCs

### Test Actor for PoCs:

```python
import asyncio
from dataclasses import dataclass, field
from time import time
from typing import Callable
from urllib.parse import urljoin

from apify import Actor
from apify.storages import RequestQueue
from bs4 import BeautifulSoup, Tag
from httpx import AsyncClient


@dataclass(frozen=True)
class ActorInput:
    start_urls: list[dict] = field(default_factory=lambda: [{'url': 'https://apify.com'}])
    max_depth: int = 1
    desired_concurrency: int = 10


class BeautifulSoupCrawler:
    def __init__(self, handle_request: Callable, max_depth: int, desired_concurrency: int) -> None:
        self.handle_request = handle_request
        self.max_depth = max_depth
        self.desired_concurrency = desired_concurrency

    async def run(self, start_urls: list) -> None:
        # Todo: every PoC will implement this differently


async def handle_request(request: dict, request_queue: RequestQueue, max_depth: int) -> None:
    url = request['url']
    depth = request['userData']['depth']
    Actor.log.info(f'Scraping {url} (depth={depth}) ...')

    try:
        async with AsyncClient() as client:
            response = await client.get(url, follow_redirects=True)
        soup = BeautifulSoup(response.content, 'html.parser')

        # If we haven't reached the max depth, look for nested links and enqueue their targets
        if depth < max_depth:
            for link in soup.find_all('a'):
                link_href = link.get('href')
                link_url = urljoin(url, link_href)
                if link_url.startswith(('http://', 'https://')):
                    Actor.log.info(f'Enqueuing {link_url} ...')
                    await request_queue.add_request(
                        {
                            'url': link_url,
                            'userData': {'depth': depth + 1},
                        }
                    )

        result = {
            'url': url,
            'title': soup.title.string if isinstance(soup.title, Tag) else None,
        }
        await Actor.push_data(result)

    except Exception:
        Actor.log.exception(f'Cannot extract data from {url}.')
    finally:
        # Mark the request as handled so it's not processed again
        await request_queue.mark_request_as_handled(request)


async def main() -> None:
    async with Actor:
        actor_input = ActorInput(**(await Actor.get_input() or {}))
        crawler = BeautifulSoupCrawler(handle_request, actor_input.max_depth, actor_input.desired_concurrency)
        start = time()
        await crawler.run(actor_input.start_urls)
        elapsed_time = time() - start
        Actor.log.info(f'Time taken: {elapsed_time}')
```

**Comment by vdusek** [comment]
### PoC v1 - fixed concurrency using `asyncio.gather`

- This solution uses `asyncio.gather` to execute a fixed number of (request processing) tasks together.
- This has a massive drawback since the `asyncio.gather` will last as long as the slowest request processing.
- In the PoC v2 I'd like to try to add tasks one by one to the event loop and use some mechanism from asyncio library to monitor the number of running tasks (e.g. `asyncio.all_tasks()`).

```python
import asyncio
from dataclasses import dataclass, field
from time import time
from typing import Callable
from urllib.parse import urljoin

from apify import Actor
from apify.storages import RequestQueue
from bs4 import BeautifulSoup
from httpx import AsyncClient

DESIRED_CONCURRENCY = 20


@dataclass(frozen=True)
class ActorInput:
    start_urls: list[dict] = field(default_factory=lambda: [{"url": "https://apify.com"}])
    max_depth: int = 1


class BeautifulSoupCrawler:
    def __init__(self, handle_request: Callable, max_depth: int) -> None:
        self.handle_request = handle_request
        self.max_depth = max_depth

    async def run(self, start_urls: list) -> None:
        request_queue = await Actor.open_request_queue()

        # Enqueue the starting URLs in the default request queue
        for start_url in start_urls:
            url = start_url.get("url")
            Actor.log.info(f"Enqueuing {url} ...")
            await request_queue.add_request({"url": url, "userData": {"depth": 0}})

        # Process all requests from the default request queue
        while not await request_queue.is_empty():
            tasks = []

            while len(tasks) < DESIRED_CONCURRENCY:
                request = await request_queue.fetch_next_request()
                if not request:
                    break
                cor = self.handle_request(request, request_queue, self.max_depth)
                task = asyncio.create_task(cor)
                tasks.append(task)

            Actor.log.info(f"Gonna process {len(tasks)} requests")
            await asyncio.gather(*tasks)


async def handle_request(request: dict, request_queue: RequestQueue, max_depth: int) -> None:
    url = request["url"]
    depth = request["userData"]["depth"]
    Actor.log.info(f"Scraping {url} (depth={depth}) ...")

    try:
        async with AsyncClient() as client:
            response = await client.get(url, follow_redirects=True)
        soup = BeautifulSoup(response.content, "html.parser")

        # If we haven't reached the max depth, look for nested links and enqueue their targets
        if depth < max_depth:
            for link in soup.find_all("a"):
                link_href = link.get("href")
                link_url = urljoin(url, link_href)
                if link_url.startswith(("http://", "https://")):
                    Actor.log.info(f"Enqueuing {link_url} ...")
                    await request_queue.add_request(
                        {
                            "url": link_url,
                            "userData": {"depth": depth + 1},
                        }
                    )

        result = {"url": url, "title": soup.title.string}
        await Actor.push_data(result)

    except Exception:
        Actor.log.exception(f"Cannot extract data from {url}.")
    finally:
        # Mark the request as handled so it's not processed again
        await request_queue.mark_request_as_handled(request)


async def main() -> None:
    async with Actor:
        start = time()
        actor_input = ActorInput(**(await Actor.get_input() or {}))
        crawler = BeautifulSoupCrawler(handle_request, actor_input.max_depth)
        await crawler.run(actor_input.start_urls)
        Actor.log.info(f"Time taken: {time() - start}")
```

**Comment by vdusek** [comment]
### PoC v2 - keep the desired concurrency using `asyncio.Semaphore`.

- This solution uses `asyncio.create_task` to create tasks for processing requests and then using `asyncio.Semaphore` it tries to keep the desired concurrency.
- I tested it with the following input on the platform, it makes ~1000 requests in total and it takes ~110 secs to be processed.
```json
{
  "start_urls": [
    { "url": "https://apify.com" },
    { "url": "https://crawlee.dev" },
    { "url": "https://python.org" },
    { "url": "https://google.com" },
    { "url": "https://bing.com" },
    { "url": "https://duckduckgo.com" },
    { "url": "https://wikipedia.org" },
    { "url": "https://facebook.com" },
    { "url": "https://instagram.com" },
    { "url": "https://linkedin.com" },
    { "url": "https://yahoo.com" },
    { "url": "https://youtube.com" }
  ],
  "max_depth": 1
}
```

- The `main.py` code of the Python Actor:

```python
import asyncio
from dataclasses import dataclass, field
from time import time
from typing import Callable
from urllib.parse import urljoin

from apify import Actor
from apify.storages import RequestQueue
from bs4 import BeautifulSoup, Tag
from httpx import AsyncClient

DESIRED_CONCURRENCY = 100


@dataclass(frozen=True)
class ActorInput:
    start_urls: list[dict] = field(default_factory=lambda: [{'url': 'https://apify.com'}])
    max_depth: int = 1


class BeautifulSoupCrawler:
    def __init__(self, handle_request: Callable, max_depth: int) -> None:
        self.handle_request = handle_request
        self.max_depth = max_depth

    async def run(self, start_urls: list) -> None:
        request_queue = await Actor.open_request_queue()

        # Enqueue the starting URLs in the request queue
        for start_url in start_urls:
            url = start_url.get('url')
            Actor.log.info(f'Enqueuing {url} ...')
            await request_queue.add_request({'url': url, 'userData': {'depth': 0}})

        # Create a semaphore to control concurrency
        semaphore = asyncio.Semaphore(DESIRED_CONCURRENCY)

        # Create a list to keep track of running tasks
        running_tasks = []

        while not await request_queue.is_empty():
            # Limit the concurrency using the semaphore
            await semaphore.acquire()

            # Fetch the next request from the request queue
            request = await request_queue.fetch_next_request()
            assert isinstance(request, dict)

            # Create a task to process the request
            coroutine = self.handle_request(request, request_queue, self.max_depth)
            task = asyncio.create_task(coroutine)
            task.add_done_callback(lambda _: semaphore.release())
            running_tasks.append(task)

            # Ensure that the desired concurrency is maintained
            while len(running_tasks) >= DESIRED_CONCURRENCY:
                await asyncio.sleep(0.1)  # Adjust the sleep duration as needed
                running_tasks = [task for task in running_tasks if not task.done()]

        # Wait for all remaining tasks to complete
        await asyncio.gather(*running_tasks)


async def handle_request(request: dict, request_queue: RequestQueue, max_depth: int) -> None:
    url = request['url']
    depth = request['userData']['depth']
    Actor.log.info(f'Scraping {url} (depth={depth}) ...')

    try:
        # Fetch the page content
        async with AsyncClient() as client:
            response = await client.get(url, follow_redirects=True)

        # Parse the page content using BeautifulSoup
        soup = BeautifulSoup(response.content, 'html.parser')

        # If we haven't reached the max depth, look for nested links and enqueue their targets
        if depth < max_depth:
            for link in soup.find_all('a'):
                link_href = link.get('href')
                link_url = urljoin(url, link_href)
                if link_url.startswith(('http://', 'https://')):
                    Actor.log.info(f'Enqueuing {link_url} ...')
                    await request_queue.add_request(
                        {
                            'url': link_url,
                            'userData': {'depth': depth + 1},
                        }
                    )

        result = {
            'url': url,
            'title': soup.title.string if isinstance(soup.title, Tag) else None,
        }
        await Actor.push_data(result)
        await request_queue.mark_request_as_handled(request)

    except Exception:
        Actor.log.exception(f'Cannot extract data from {url}.')


async def main() -> None:
    async with Actor:
        start = time()
        actor_input = ActorInput(**(await Actor.get_input() or {}))
        crawler = BeautifulSoupCrawler(handle_request, actor_input.max_depth)
        await crawler.run(actor_input.start_urls)
        Actor.log.info(f'Time taken: {time() - start}')
```

**Comment by vdusek** [comment]
@jirimoravcik, @fnesveda If you guys please look at that, I'll be glad for any feedback, concerns, opinions... Thanks.

**Comment by fnesveda** [comment]
For the fixed concurrency this looks pretty good, but I'm afraid that adapting this to dynamic concurrency will require a big rewrite, as `asyncio.Semaphore` doesn't support changing the limit while it's running. Maybe we could implement our own version which would support that, it doesn't look like the [current implementation](https://github.com/python/cpython/blob/0887b9ce8b5b4f9ecdef014b9329da78a46c9f42/Lib/asyncio/locks.py#L330) is too complicated.

Also I think in the end we would like the Python `AutoscaledPool` to have a similar interface to the JS `AutoscaledPool`, and we'll have to adapt the concurrency approach to that interface too. For that interface, the approach from the [post from Jirka](https://death.andgravity.com/limit-concurrency) would work better.

So perhaps in PoC v3 you could create some simple `AutoscaledPool` class with a similar interface to the JS one, without the actual scaling based on CPU and memory, and then you could choose the best concurrency approach that works with that.

**Comment by vdusek** [comment]
Thanks. Yeah... I definitely want to stick to the interface of JS AutoscaledPool, this was just a first pitch trying to process the requests somehow concurrently. The post is great, I'll write tomorrow the PoC v3 utilizing `asyncio.wait` :muscle:.

**Comment by vdusek** [comment]
### PoC v3 - `asyncio.wait`

- This crawler uses `asyncio.create_task` to create tasks for processing requests, and then utilizing `asyncio.Semaphore` keeps the desired concurrency.

```python
class BeautifulSoupCrawler:

    def __init__(self, handle_request: Callable, max_depth: int, desired_concurrency: int) -> None:
        self.handle_request = handle_request
        self.max_depth = max_depth
        self.desired_concurrency = desired_concurrency

    async def run(self, start_urls: list) -> None:
        request_queue = await Actor.open_request_queue()

        # Enqueue the starting URLs in the request queue
        for start_url in start_urls:
            url = start_url.get('url')
            Actor.log.info(f'Enqueuing {url} ...')
            await request_queue.add_request({'url': url, 'userData': {'depth': 0}})

        # Create a list to keep track of running tasks
        running_tasks: set[asyncio.Task] = set()

        # Process all the requests
        while True:
            # Check if there is room for more tasks
            while len(running_tasks) >= self.desired_concurrency:
                done, _ = await asyncio.wait(running_tasks, return_when=asyncio.FIRST_COMPLETED)
                running_tasks -= done  # Remove completed tasks from the set

            # Start processing the next request from the request queue
            if request := await request_queue.fetch_next_request():
                assert isinstance(request, dict)

                # Create a task to process the request
                cor = self.handle_request(request, request_queue, self.max_depth)
                task = asyncio.create_task(cor)
                running_tasks.add(task)  # Add the task to the set

            # Else request queue is empty...
            else:
                # In this case we have to wait for all running tasks to complete since they can enqueue more requests
                Actor.log.info('Waiting for running tasks to complete...')
                done, _ = await asyncio.wait(running_tasks, return_when=asyncio.ALL_COMPLETED)
                running_tasks -= done
                assert len(running_tasks) == 0

                # Request queue is empty and there are no running tasks, we are done
                if await request_queue.is_empty():
                    Actor.log.info('Breaking...')
                    break

        # Make sure that all running tasks are completed and the request queue is empty
        assert len(running_tasks) == 0
        assert (await request_queue.is_empty()) is True
```

**Comment by vdusek** [comment]
### PoC v0 - the current state

- Just processing the requests one at a time as we do in the Actor templates.

```python
from typing import Callable

from apify import Actor


class BeautifulSoupCrawler:
    
    def __init__(self, handle_request: Callable, max_depth: int, desired_concurrency: int) -> None:
        self.handle_request = handle_request
        self.max_depth = max_depth
        self.desired_concurrency = desired_concurrency

    async def run(self, start_urls: list) -> None:
        request_queue = await Actor.open_request_queue()

        # Enqueue the starting URLs in the request queue
        for start_url in start_urls:
            url = start_url.get('url')
            Actor.log.info(f'Enqueuing {url} ...')
            await request_queue.add_request({'url': url, 'userData': {'depth': 0}})

        # Process all requests from the request queue one by one
        while request := await request_queue.fetch_next_request():
            await self.handle_request(request, request_queue, self.max_depth)
```

**Comment by vdusek** [comment]
@jirimoravcik, @fnesveda A PoC v3 using the `asyncio.wait` is ready. 

I also did some testing with the following configuration:
  - Desired concurrency: 10
  - Total requests made: 90
  - Input:
```json
{
  "start_urls": [
    { "url": "https://apify.com" },
    { "url": "https://crawlee.dev" }
  ],
  "max_depth": 1
}
```

### PoC v0:
- Locally:
    - Time taken: 30s 
- On platform:
    - Time taken: 29.4s
    - Run: https://api.apify.com/v2/logs/pnwYORPvkePZJdTNZ
    
### PoC v1 - `asyncio.gather`:
- Locally:
    - Time taken: 10.5s
- On platform:
    - Time taken: 11s
    - Run: https://api.apify.com/v2/logs/actoY1zvIIKxSFnKN

### PoC v2 - `asyncio.Semaphore`:
- Locally:
    - Time taken: 5.7s
- On platform:
    - Time taken: 13.7s
    - Run: https://api.apify.com/v2/logs/vQY8g4kqBFkdGLsbT

### PoC v3 - `asyncio.wait`:
- Locally:
    - Time taken: 4.75s
- On platform:
    - Time taken: 13.6s
    - Run: https://api.apify.com/v2/logs/ffjGcWGjwtBYIOMUh 

Of course, the only weird thing is the difference between local and platform execution time of Semaphore & wait solutions. I tried it many times, everytime resulting in the similar times. Do you have guys any idea what it causes?

**Comment by jirimoravcik** [comment]
Maybe run each variant 100 times to get some statistical significance?

**Comment by janbuchar** [comment]
> Maybe run each variant 100 times to get some statistical significance?

I'd even consider running the benchmark against some local mock HTTP service. My personal guess is that any difference between v2 and v3 is caused by the unpredictability of network delays.

**Comment by vdusek** [comment]
## Measure the performance of the PoCs

- All of the 4 variants were built as an Actor version on the platform.
- Every variant was executed 75x on the platform with the configuration below.
- In every Actor run 90 requests were made.

### Configuration
- `desired_concurrency = 10`
- `start_urls = [{ "url": "https://apify.com" }, { "url": "https://crawlee.dev" }]`
- `max_depth = 1`

### Results

- Average time of running `crawler.run()`.

```json
{
  "crawler_basic": 41.2554286702474,
  "crawler_gather": 22.39655220667521,
  "crawler_semaphore": 15.280439224243164,
  "crawler_wait": 13.826195780436198
}
```

### Summary

- So as expected `semaphore` and `wait` variants outperformed the `gather`, and of course the `basic`.
- Since `wait` variant also supports a dynamic change of the concurrency, it seems like a clear winner for further steps.
- I'm closing this issue and moving on to the next steps, as outlined in the follow-up issue https://github.com/apify/apify-sdk-python/issues/131.
