### ISSUE TITLE
Switch to Ruff (linter & formatter)

### ISSUE THREAD

**Issue by vdusek** [apify/apify-sdk-python#128]
Ruff is a new extremely fast Python linter written in Rust, which supports many rules from the `flake8` & `pylint` world.

They recently released a formatter, where single quotes are an option :).

### Task list

- [ ] Install the `ruff`, and update the configs & code to be aligned with the linter rules.
- [ ] Update the GH workflows.
- [ ] Do the same for the `apify-client-python` and `apify-shared-python` libraries.
